name: Publish Package to npmjs
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Automatic GitHub Release
        uses: justincy/github-action-npm-release@2.0.1
        id: release
      - uses: actions/setup-node@v3
        if: steps.release.outputs.released == 'true'
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish
        if: steps.release.outputs.released == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}